export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'
export const SET_CART_PRICES = 'SET_CART_PRICES'

export const ADD_TOKEN = 'ADD_TOKEN'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE'